# Generated by Django 4.2.30 on 2026-05-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('learner', 'Learner'), ('mentor', 'Mentor')], default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='sessions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('certificate_type__in', ['learner', 'mentor']), ('exchange__isnull', False)), fields=('user', 'exchange'), name='unique_role_certificate_per_user_exchange'),
        ),
    ]
