# Generated by Codex on 2026-05-19

from django.db import migrations, models
from django.db.models import Count


def backfill_certificate_type(apps, schema_editor):
    Certificate = apps.get_model("engagement", "Certificate")
    Certificate.objects.filter(certificate_type__isnull=True).update(
        certificate_type="learner_completion"
    )
    Certificate.objects.filter(certificate_type="").update(
        certificate_type="learner_completion"
    )
    Certificate.objects.filter(certificate_type="legacy").update(
        certificate_type="learner_completion"
    )
    Certificate.objects.filter(certificate_type="learner").update(
        certificate_type="learner_completion"
    )
    Certificate.objects.filter(certificate_type="mentor").update(
        certificate_type="mentor_contribution"
    )

    duplicate_groups = (
        Certificate.objects.filter(
            exchange__isnull=False,
            certificate_type__in=["learner_completion", "mentor_contribution"],
        )
        .values("user_id", "exchange_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for group in duplicate_groups:
        certificates = Certificate.objects.filter(
            user_id=group["user_id"],
            exchange_id=group["exchange_id"],
            certificate_type__in=["learner_completion", "mentor_contribution"],
        ).order_by("-sessions_count", "-hours_completed", "id")
        keeper = certificates.first()
        certificates.exclude(pk=keeper.pk).delete()


def reverse_certificate_type_values(apps, schema_editor):
    Certificate = apps.get_model("engagement", "Certificate")
    Certificate.objects.filter(certificate_type="learner_completion").update(
        certificate_type="learner"
    )
    Certificate.objects.filter(certificate_type="mentor_contribution").update(
        certificate_type="mentor"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0002_certificate_certificate_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="certificate",
            name="unique_role_certificate_per_user_exchange",
        ),
        migrations.AlterField(
            model_name="certificate",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("learner_completion", "Learner Completion"),
                    ("mentor_contribution", "Mentor Contribution"),
                ],
                default="learner_completion",
                max_length=30,
            ),
        ),
        migrations.RunPython(backfill_certificate_type, reverse_certificate_type_values),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("certificate_type__in", ["learner_completion", "mentor_contribution"]),
                    ("exchange__isnull", False),
                ),
                fields=("user", "exchange"),
                name="unique_role_certificate_per_user_exchange",
            ),
        ),
    ]
