# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0003_update_certificate_type_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("learner_completion", "Learner Completion"),
                    ("mentor_contribution", "Mentor Recognition"),
                ],
                default="learner_completion",
                max_length=30,
            ),
        ),
    ]
