# Generated by Django 6.0.5 on 2026-05-14 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='matchrequest',
            name='unique_pending_match_request',
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='offered_skill',
            field=models.ForeignKey(blank=True, help_text='Skill the sender can teach in exchange.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests_offered', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='requested_skill',
            field=models.ForeignKey(blank=True, help_text='Skill the sender wants to learn from the receiver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests_requested', to='skills.skill'),
        ),
        migrations.AddConstraint(
            model_name='matchrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'receiver', 'offered_skill', 'requested_skill'), name='unique_pending_exchange_request'),
        ),
        migrations.AddField(
            model_name='skillexchange',
            name='offered_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_exchanges_offered', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='skillexchange',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange', to='matching.matchrequest'),
        ),
        migrations.AddField(
            model_name='skillexchange',
            name='requested_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_exchanges_requested', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='skillexchange',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_skill_exchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillexchange',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responded_skill_exchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='skillexchange',
            constraint=models.UniqueConstraint(fields=('requester', 'responder', 'offered_skill', 'requested_skill'), name='unique_active_skill_exchange'),
        ),
    ]
