# Generated by Django 4.2.30 on 2026-05-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_skillexchange_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matchrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('sender', 'receiver', 'offered_skill', 'requested_skill'), name='unique_active_exchange_request'),
        ),
    ]
